#!/usr/bin/env bash
# Why: install Caddy's internal CA in the host trust stores so the browser
# stops showing the "Your connection is not private" page, AND so that
# Node.js / Electron clients (Codebuddy, Codex/ChatGPT, VSCode MCP clients,
# Claude Code, anything that uses `fetch` from undici / Node 18+) can also
# verify Caddy's self-signed cert. The CA is generated by Caddy on first boot
# and surfaced at ./data/caddy/pki/authorities/local/root.crt — a path this
# script derives from its own location, so it works in any checkout.
#
# Why four stores on Linux:
#   * /usr/local/share/ca-certificates → /etc/ssl/certs is what *system*
#     OpenSSL (curl, wget, openssl s_client) consults.
#   * ~/.pki/nssdb is what Chromium-based browsers (Chrome / Edge, and
#     Playwright's bundled Chrome for Testing) consult for *user* trust
#     anchors. Installing only into the system store is NOT enough to make
#     Chromium/Playwright stop showing `ERR_CERT_AUTHORITY_INVALID` — you
#     also have to `certutil -A` into the per-user NSS DB.
#   * Firefox keeps a SEPARATE per-profile NSS DB (~/.mozilla/firefox/*/
#     cert9.db) and ignores the system store and ~/.pki/nssdb entirely, so
#     the CA has to be imported into each Firefox profile individually.
#   * Node.js / Electron ignore the system OpenSSL store AND the NSS DB.
#     They use a CA bundle compiled into the Node binary. To add a custom
#     CA you MUST point `NODE_EXTRA_CA_CERTS` at it (Node >= 17.4). Without
#     this, MCP clients using SSE/streamable HTTP against
#     https://penpot.local/* fail with:
#       SSE error: TypeError: fetch failed:
#       unable to get local issuer certificate
#     We export NODE_EXTRA_CA_CERTS in three places so it reaches both
#     shell-spawned processes (zsh login env, bash login env) and
#     GUI-spawned Electron apps (VSCode / Codex / Codebuddy launched from
#     the desktop launcher or by systemd, which read /etc/environment).

# Why: these scripts use bash arrays and ${BASH_SOURCE}. Re-exec under bash when
# someone starts them with `sh script.sh` (dash on Debian/Ubuntu) so they behave
# identically no matter how they are invoked.
[ -n "${BASH_VERSION:-}" ] || exec bash "$0" "$@"

set -euo pipefail

# Why: resolve this script's real location (following symlinks, e.g. a copy
# linked into ~/bin) before sourcing lib.sh — a symlinked invocation would
# otherwise look for lib.sh next to the link instead of inside the checkout.
# shellcheck source=lib.sh
_lib_src="${BASH_SOURCE[0]}"
while [ -L "$_lib_src" ]; do
  _lib_link="$(readlink "$_lib_src")"
  case "$_lib_link" in /*) _lib_src="$_lib_link";; *) _lib_src="$(dirname -- "$_lib_src")/$_lib_link";; esac
done
source "$(cd -- "$(dirname -- "$_lib_src")" >/dev/null 2>&1 && pwd -P)/lib.sh"

CA_FILE="$CA_CERT"
CERT_NICK="Caddy Local Root"

if [ ! -f "$CA_FILE" ]; then
  echo "Caddy CA not found at $CA_FILE"
  echo "Start the stack first so Caddy can generate its internal CA:"
  echo "  ./scripts/up.sh"
  exit 1
fi

# Why: every verification below compares FINGERPRINTS, never nicknames.
# Each deployment directory generates its own Caddy CA, so moving the checkout
# (or running a second one) replaces the CA. The old CA stays behind under the
# *same* nickname "Caddy Local Root", so a nickname-based "is it installed?"
# check reports success while the browser still rejects the site — that was
# exactly the bug: `certutil -L | grep Caddy Local Root` matched the stale cert.
CA_FP="$(openssl x509 -in "$CA_FILE" -noout -fingerprint -sha256 2>/dev/null | sed 's/^.*=//')"
if [ -z "$CA_FP" ]; then
  echo "ERROR: cannot parse the CA certificate at $CA_FILE (is openssl installed?)" >&2
  exit 1
fi

fp_of() { # read a PEM on stdin, print its SHA256 fingerprint
  openssl x509 -noout -fingerprint -sha256 2>/dev/null | sed 's/^.*=//'
}

# Why: split a PEM bundle and compare every member by fingerprint. Note that
# `openssl pkcs7 -print_certs` only prints subject/issuer — it emits no
# fingerprint, so it cannot be used for this comparison.
bundle_has_ca() { # $1 = PEM bundle
  local bundle="$1" tmpdir pem
  [ -f "$bundle" ] || return 1
  tmpdir="$(mktemp -d)"
  awk -v d="$tmpdir" '/BEGIN CERTIFICATE/ {n++} n>0 {print > (d "/c" n ".pem")}' "$bundle" 2>/dev/null
  for pem in "$tmpdir"/c*.pem; do
    [ -f "$pem" ] || continue
    if [ "$(openssl x509 -in "$pem" -noout -fingerprint -sha256 2>/dev/null | sed 's/^.*=//')" = "$CA_FP" ]; then
      rm -rf "$tmpdir"
      return 0
    fi
  done
  rm -rf "$tmpdir"
  return 1
}

# Why: NSS keeps every cert we ever added, so re-running against a new
# deployment leaves a growing pile of same-nickname anchors. Delete ours first,
# then add — that also avoids certutil silently appending a duplicate nickname.
nss_has_ca() { # $1 = NSS dir
  local db="$1" nick
  while IFS= read -r nick; do
    [ -n "$nick" ] || continue
    if certutil -L -d sql:"$db" -n "$nick" -a 2>/dev/null | fp_of | grep -qiF "$CA_FP"; then
      return 0
    fi
  done < <(certutil -L -d sql:"$db" 2>/dev/null | grep -F "$CERT_NICK" | sed "s/[[:space:]]*\$//;s/[[:space:]]*[A-Za-z,]*\$//" | sort -u)
  return 1
}

nss_install_ca() { # $1 = NSS dir, $2 = trust args
  local db="$1" trust="$2" nick
  # Remove every entry previously installed under our nickname.
  while IFS= read -r nick; do
    [ -n "$nick" ] || continue
    certutil -D -d sql:"$db" -n "$nick" >/dev/null 2>&1 || true
  done < <(certutil -L -d sql:"$db" 2>/dev/null | grep -F "$CERT_NICK" | sed "s/[[:space:]]*\$//;s/[[:space:]]*[A-Za-z,]*\$//" | sort -u)
  certutil -A -d sql:"$db" -t "$trust" -n "$CERT_NICK" -i "$CA_FILE" >/dev/null 2>&1
  if nss_has_ca "$db"; then
    echo "  trusted (verified by fingerprint): $db"
    return 0
  fi
  echo "  WARNING: import did not take effect in $db" >&2
  return 1
}



# Why: NODE_EXTRA_CA_CERTS needs an absolute path — a relative one is resolved
# against whatever CWD the app was launched from.
ABS_CA="$(cd -- "$(dirname -- "$CA_FILE")" >/dev/null 2>&1 && pwd -P)/$(basename -- "$CA_FILE")"

# Why: these blocks are appended to files the user owns. Keep the marker
# generic (no absolute checkout path) so the block stays accurate when the
# repository is cloned somewhere else.
MARKER="penpot scripts/trust-ca.sh"

# Why: the checkout can move (or a second one can appear), and each location
# yields a different CA path. Appending a block every time would leave several
# stale NODE_EXTRA_CA_CERTS exports behind, where the last one silently wins.
# Strip our previous block first so the file holds exactly one live entry.
strip_previous_block() {
  local file="$1" skip_after_marker="$2" tmp
  [ -f "$file" ] || return 0
  tmp="$(mktemp)"
  awk -v marker="$MARKER" -v skip="$skip_after_marker" '
    BEGIN { pending = 0 }
    {
      if (pending > 0) { pending--; next }
      if ($0 ~ /^# Added by / && index($0, marker)) { pending = skip; next }
      if ($0 ~ /NODE_EXTRA_CA_CERTS/ && $0 ~ /data\/caddy/) { next }
      print
    }
  ' "$file" > "$tmp"
  cat "$tmp" > "$file"
  rm -f "$tmp"
}

write_env_line() {
  local file="$1" line="$2"
  [ -f "$file" ] || touch "$file"
  if grep -F -q "$ABS_CA" "$file" 2>/dev/null; then
    echo "$file already references $ABS_CA"
    return 0
  fi
  # Drop the block a previous run of this script appended (3 comment lines +
  # the export line), then append a freshly-marked one.
  strip_previous_block "$file" 3
  # printf with %s placeholders so the apostrophe in "Caddy's" cannot break
  # the single-quoted argv below.
  printf '\n# Added by %s so Node.js /\n# Electron (Codebuddy / Codex / VSCode) can verify Caddy%ss self-signed\n# CA at https://%s. Remove this block to undo.\n%s\n' \
    "$MARKER" "'" "$HOST_NAME" "$line" >> "$file"
  echo "NODE_EXTRA_CA_CERTS appended to $file"
}

case "$OSTYPE" in
  linux-gnu*|linux*)
    need_privileges || echo "NOTE: no root/sudo available — system trust store will be skipped."

    # 1) System trust store (Debian/Ubuntu, and anything shipping
    #    update-ca-certificates) — used by curl/openssl.
    if command -v update-ca-certificates >/dev/null 2>&1; then
      TARGET_DIR="/usr/local/share/ca-certificates"
      TARGET="$TARGET_DIR/penpot-caddy.crt"
      if [ -n "$SUDO" ] || [ "$(id -u)" = "0" ]; then
        run_privileged cp "$CA_FILE" "$TARGET"
        run_privileged update-ca-certificates >/dev/null 2>&1
        # Why: verify by fingerprint against the live bundle. update-ca-certificates
        # takes no notice of a cert whose subject hash it already has (two Caddy
        # roots share the subject "Caddy Local Authority - <year> ECC Root"), so a
        # plain "0 added, 0 removed" tells us nothing about which CA is installed.
        if bundle_has_ca /etc/ssl/certs/ca-certificates.crt; then
          echo "  trusted (verified by fingerprint): $TARGET"
        else
          echo "  WARNING: $CA_FILE is not in /etc/ssl/certs/ca-certificates.crt" >&2
        fi
      else
        echo "WARNING: cannot write $TARGET — skipping system trust store."
      fi
    else
      echo "NOTE: update-ca-certificates not found — skipping system trust store"
      echo "  (this host is not Debian/Ubuntu; copy $CA_FILE into your distro's store)."
    fi

    # 2) User NSS DB — used by Chromium / Chrome / Edge / Chrome for Testing
    #    (Playwright). `certutil` ships with libnss3-tools; install it if missing.
    NSS_DB="$HOME/.pki/nssdb"
    if [ -d "$NSS_DB" ]; then
      if ! command -v certutil >/dev/null 2>&1; then
        echo "  certutil not found — skipped. Install libnss3-tools so"
        echo "  Chromium-based browsers (Chrome / Edge / Playwright) can trust the CA:"
        echo "    sudo apt-get install -y libnss3-tools"
      else
        # CT,C,C = trusted for TLS server auth + email + code signing.
        nss_install_ca "$NSS_DB" "CT,C,C"
      fi
    fi

    # 3) Firefox — uses its OWN per-profile NSS cert9.db, NOT the system
    #    store and NOT ~/.pki/nssdb. Import the CA into every non-empty
    #    Firefox profile so the "Your connection is not secure" page goes away.
    #    `C,,` = trusted for TLS server auth only.
    if command -v certutil >/dev/null 2>&1; then
      for FF_DB in "$HOME"/.mozilla/firefox/*/cert9.db; do
        [ -f "$FF_DB" ] || continue
        FF_DIR="$(dirname "$FF_DB")"
        certutil -L -d sql:"$FF_DIR" >/dev/null 2>&1 || continue
        nss_install_ca "$FF_DIR" "C,,"
      done
    else
      echo "  certutil not found — skipped Firefox profiles. Install:"
      echo "    sudo apt-get install -y libnss3-tools"
    fi

    # Why: list any OTHER Caddy CA still trusted. These are leftovers from
    # previous checkouts and are harmless on their own, but they are what the
    # browser may still be pinning its trust to after a deployment move.
    STALE="$(ls /usr/local/share/ca-certificates 2>/dev/null | grep -i caddy || true)"
    if [ -n "$STALE" ]; then
      echo
      echo "Other Caddy root(s) in the system store (from older deployments):"
      for f in /usr/local/share/ca-certificates/*[Cc]addy*; do
        [ -f "$f" ] || continue
        if openssl x509 -in "$f" -noout -fingerprint -sha256 2>/dev/null | sed 's/^.*=//' | grep -qiF "$CA_FP"; then
          continue
        fi
        printf '  %s  %s\n' "$(openssl x509 -in "$f" -noout -fingerprint -sha1 2>/dev/null | sed 's/^.*=//')" "$f"
      done
      echo "  They are unrelated to this checkout. Remove the ones you no longer need"
      echo "  and re-run update-ca-certificates if you want a clean store."
    fi

    echo "Restart your browsers to pick up the changes."

    # 4) Node.js / Electron trust store. System OpenSSL/NSS stores do NOT
    #    help here: Node uses its own compiled CA bundle. Setting
    #    NODE_EXTRA_CA_CERTS adds extra trust anchors on top of the built-in
    #    bundle (Node >= 17.4 / Electron >= 17). This fixes
    #    "fetch failed: unable to get local issuer certificate" for MCP
    #    clients (Codebuddy / Codex / VSCode / Claude Code / etc.) that hit
    #    https://penpot.local/...
    EXPORT_LINE="export NODE_EXTRA_CA_CERTS=\"$ABS_CA\""
    write_env_line "$HOME/.zshenv" "$EXPORT_LINE"
    write_env_line "$HOME/.bashrc" "$EXPORT_LINE"

    # /etc/environment covers processes launched by the desktop session
    # (Activities / GNOME Shell / systemd --user), where neither .zshenv
    # nor .bashrc apply. /etc/environment is key=value lines, no `export`.
    ETC_ENV="/etc/environment"
    if [ -f "$ETC_ENV" ]; then
      if grep -F -q "$ABS_CA" "$ETC_ENV" 2>/dev/null; then
        echo "$ETC_ENV already references $ABS_CA"
      elif [ -n "$SUDO" ] || [ "$(id -u)" = "0" ]; then
        # /etc/environment is key=value, no `export`, so our block is a 1-line
        # comment + 1 line value. Strip the previous one before appending.
        _tmp="$(mktemp)"
        awk -v marker="$MARKER" '
          BEGIN { pending = 0 }
          {
            if (pending > 0) { pending--; next }
            if ($0 ~ /^# Added by / && index($0, marker)) { pending = 1; next }
            if ($0 ~ /NODE_EXTRA_CA_CERTS/ && $0 ~ /data\/caddy/) { next }
            print
          }
        ' "$ETC_ENV" > "$_tmp"
        printf '\n# Added by %s\nNODE_EXTRA_CA_CERTS="%s"\n' "$MARKER" "$ABS_CA" >> "$_tmp"
        run_privileged cp "$_tmp" "$ETC_ENV"
        rm -f "$_tmp"
        echo "NODE_EXTRA_CA_CERTS written to $ETC_ENV"
      else
        echo "WARNING: cannot write $ETC_ENV — GUI-launched apps will not inherit the CA."
        echo "  Add manually:  NODE_EXTRA_CA_CERTS=\"$ABS_CA\""
      fi
    else
      echo "NOTE: $ETC_ENV not found — skipping (not a systemd/PAM host)."
    fi

    # Also export it in the current shell so anything spawned from THIS
    # terminal (the user's existing session) picks it up without a restart.
    export NODE_EXTRA_CA_CERTS="$ABS_CA"
    echo "NODE_EXTRA_CA_CERTS exported in current shell: $NODE_EXTRA_CA_CERTS"

    # Why: the check that actually matters. Everything above proves files were
    # copied; only this proves what the SERVER hands out is signed by the CA we
    # just installed. When a deployment is moved, Caddy generates a brand new CA
    # and this is the one place that catches the resulting browser error.
    if command -v openssl >/dev/null 2>&1; then
      served="$(echo | openssl s_client -connect 127.0.0.1:443 \
                   -servername "$HOST_NAME" -showcerts 2>/dev/null)"
      if [ -n "$served" ]; then
        leaf="$(mktemp)"; rest="$(mktemp)"
        printf '%s\n' "$served" | awk '
          /BEGIN CERTIFICATE/ {n++}
          n==1 {print > LEAF}
          n>1  {print > REST}
        ' LEAF="$leaf" REST="$rest"
        if openssl verify -CAfile "$CA_FILE" -untrusted "$rest" "$leaf" >/dev/null 2>&1; then
          echo "Chain check OK: the certificate served on https://${HOST_NAME} validates against $CA_FILE."
        else
          echo "Chain check FAILED: the server is NOT presenting a certificate signed by" >&2
          echo "  $CA_FILE" >&2
          echo "  This means the running deployment uses a different Caddy CA — most likely" >&2
          echo "  because it has its own data/ directory, or the stack was re-created after" >&2
          echo "  this CA file was read. Run ./scripts/status.sh to see which CA is live." >&2
        fi
        rm -f "$leaf" "$rest"
      else
        echo "Chain check skipped: nothing is listening on 127.0.0.1:443 (stack not running)."
      fi
    fi

    # Sanity check: prove a TLS fetch against Penpot works from Node.
    if command -v node >/dev/null 2>&1; then
      if node -e "fetch('https://${HOST_NAME}/api/main/methods/get-enabled-flags').then(r => process.exit(r.status === 401 ? 0 : 1)).catch(e => process.exit(2))" 2>/dev/null; then
        echo "Sanity check OK: Node.js fetch against https://${HOST_NAME} succeeds."
      else
        echo "Sanity check FAILED: NODE_EXTRA_CA_CERTS is set but Node still cannot reach https://${HOST_NAME}."
        echo "If you see 'fetch failed: unable to get local issuer certificate', restart the Electron app"
        echo "(VSCode / Codex / Codebuddy) so it inherits the new env var."
      fi
    fi
    ;;
  darwin*)
    sudo security add-trusted-cert -d -r trustRoot \
      -k /Library/Keychains/System.keychain "$CA_FILE"
    # macOS path: NODE_EXTRA_CA_CERTS is the same fix for Node-based MCP
    # clients. Add it to ~/.zshrc (default macOS shell) and ~/.bash_profile
    # (legacy bash login) so Electron apps inherit it on next launch.
    EXPORT_LINE="export NODE_EXTRA_CA_CERTS=\"$ABS_CA\""
    for f in "$HOME/.zshrc" "$HOME/.bash_profile"; do
      [ -f "$f" ] || touch "$f"
      grep -F -q "$ABS_CA" "$f" 2>/dev/null || \
        printf '\n# Added by %s\n%s\n' "$MARKER" "$EXPORT_LINE" >> "$f"
    done
    export NODE_EXTRA_CA_CERTS="$ABS_CA"
    echo "NODE_EXTRA_CA_CERTS=$NODE_EXTRA_CA_CERTS"
    echo "Restart your browser AND Electron MCP clients (VSCode / Codex) to pick up the changes."
    ;;
  *)
    echo "Auto-install not implemented for $OSTYPE — copy $CA_FILE to your"
    echo "OS trust store manually, or use 'curl --cacert $CA_FILE' from CLI."
    ;;
esac
